[machines]
VM ansible_connection=local install_gui=true
MacbookPro-13 ansible_connection=local install_gui=true
rpi5-8 ansible_connection=local install_gui=false
libre-sweetpotato ansible_connection=local install_gui=false
T430 ansible_connection=local install_gui=true